config/routes.rb
Rails.application.routes.draw do
  root to: 'themes#index'

  resources :themes, only: [:show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/theme.rb
class Theme < ApplicationRecord
  TOP_CONTENTS = {
    content1: "コンテンツ1",
    content2: "コンテンツ2",
    content3: "コンテンツ3"
  }
  TOP_CONTENTS_DEFAULT_ORDER = TOP_CONTENTS.keys

  serialize :contents_order, Hash
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update]
  before_action :set_contents_order, only: [:show, :edit]
  
  def index
    @themes = Theme.all
  end

  def show
  end

  def edit
  end

  def update
    if @theme.update(theme_params)
      redirect_to @theme
    else
      render "edit"
    end
  end

  private

    def theme_params
      params.require(:theme).permit(:name, contents_order: {})
    end

    def set_theme
      @theme = Theme.find(params[:id])
    end

    def set_contents_order
      if @theme.contents_order.empty?
        Theme::TOP_CONTENTS_DEFAULT_ORDER.each.with_index(1) do |key, index|
          @theme.contents_order[key] = index
        end
      else
        @theme.contents_order = @theme.contents_order.sort_by{ |k, v| -v }.to_h
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestReplacement</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/themes/_content1.html.slim
h2 コンテンツ1

app/views/themes/_content2.html.slim
h2 コンテンツ2

app/views/themes/_content3.html.slim
h2 コンテンツ3

app/views/themes/_form.html.slim
= form_for @theme do |f|
  ul
  - @theme.errors.full_messages.each do |error_msg|
    li = error_msg
  - @theme.contents_order.each do |key, value|
    p
      = Theme::TOP_CONTENTS[key.to_sym]
      | :
      = f.number_field :contents_order, name: "theme[contents_order][#{key}]", value: value
  = f.submit

app/views/themes/edit.html.slim
h1 コンテンツの順序の変更
= render "form"
p = link_to "戻る", root_path

app/views/themes/index.html.slim
h1 テーマ一覧
- @themes.each do |theme|
  p = link_to theme.name, theme
  p = link_to "編集する", edit_theme_path(theme)

app/views/themes/show.html.slim
h1 コンテンツの順序確認
- @theme.contents_order.each do |key, value|
  = render "#{key}"
p = link_to "戻る", root_path